-include device/semc/msm7x27-common/BoardConfigCommon.mk

TARGET_BOOTLOADER_BOARD_NAME := delta
TARGET_OTA_ASSERT_DEVICE := E10i,E10a,robyn
PRODUCT_BUILD_PROP_OVERRIDES += TARGET_BOOTLOADER_BOARD_NAME=robyn

BOARD_HAS_SMALL_RECOVERY := true
BOARD_LDPI_RECOVERY := true

## TWRP
DEVICE_RESOLUTION := 240x320
